spring:
  data:
    cassandra:
      keyspace-name: main
      username: EHhOMiBPAzscCiFLUQUYOcTT
      password: Gnm15.fMrKnLJg-JXRw_MaTObfDD.H795i9iOw7vUie3aMeX-1cumeLDT-D-+eZOe7X,cl4heCMQw_2X9FZFjGeHxD3,BHBkqeP4a4G9XWlvI11l6HZAMo_6DmmopJpf
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datadump:
    location:
      author: C:\Users\ĐorđeVitković\Desktop\Spring-Cassandra\test-authors.txt
      works: C:\Users\ĐorđeVitković\Desktop\Spring-Cassandra\test-works.txt

datastax.astra:
  secure-connect-bundle: secure-connect-betterreads.zip

astra.db:
    id: 7f99626a-93b0-4e7f-ad48-7cad300b07a2-1
    region: europe-west1
    keyspace: main
    application-token: AstraCS:EHhOMiBPAzscCiFLUQUYOcTT:044897ef4223e3d5a4a2a23ef6aea764143afd27757eccdfcb9538513197adb0


